# Generated by Django 3.2.9 on 2021-12-04 13:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 4, 13, 41, 17, 366188, tzinfo=utc)),
        ),
    ]
