# Generated by Django 3.2.9 on 2021-12-04 13:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import forum.models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='images/board_icons')),
                ('topic_count', models.IntegerField(blank=True, default=0, verbose_name='Topic count')),
                ('followers', models.ManyToManyField(blank=True, related_name='board_followers', to=settings.AUTH_USER_MODEL, verbose_name='Board_Followers')),
                ('moderators', models.ManyToManyField(blank=True, related_name='board_moderators', to=settings.AUTH_USER_MODEL, verbose_name='Moderators')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0, verbose_name='How many views')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='Order')),
                ('post_count', models.IntegerField(blank=True, default=0, verbose_name='Post count')),
                ('status', models.CharField(default='Open', max_length=20, verbose_name='Status')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(blank=True, related_name='thread_followers', to=settings.AUTH_USER_MODEL, verbose_name='Topic Followers')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Topic',
                'ordering': ('date_created',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='Write something here', max_length=4098)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='User IP')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Post Liked By')),
                ('shared_by', models.ManyToManyField(blank=True, related_name='post_shares', to=settings.AUTH_USER_MODEL, verbose_name='Post Shared By')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_posts', to='forum.topic')),
            ],
            options={
                'verbose_name': 'Post',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=forum.models.post_img_directory, validators=[forum.models.validate_image])),
                ('file', models.FileField(blank=True, null=True, upload_to=forum.models.post_img_directory, validators=[forum.models.validate_image])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.post')),
            ],
        ),
    ]
